language: go

# install - install hugo
install:
    - go get github.com/gohugoio/hugo

before_script:
    - rm -rf public 2> /dev/null

# script - run the build script
script:
    - hugo

# need to add post build for the search functionality...

deploy:
  provider: pages
  local_dir: public
  github_token: "$GH_TOKEN"
  skip_cleanup: true
  verbose: true
  keep-history: true
  on:
    branch: theme-update # to adapt
