language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

before_install:
  - sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

# install - install hugo
install:
    - go get github.com/gohugoio/hugo
    - npm install lunr glob

before_script:
    - rm -rf public 2> /dev/null

# script - run the build script
script:
    - hugo

# need to add post build for the search functionality...
before_deploy:
    - node themes/minimo/scripts/generate-search-index-lunr.js

deploy:
  provider: pages
  local_dir: public
  github_token: "$GH_TOKEN"
  skip_cleanup: true
  verbose: true
  keep-history: true
  on:
    branch: master # to adapt
