language: go

# install - install hugo
install:
    - go get github.com/gohugoio/hugo
    - curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - sudo apt-get install -y build-essential
    - npm install -g lunr glob

before_script:
    - rm -rf public 2> /dev/null

# script - run the build script
script:
    - hugo

# need to add post build for the search functionality...
before_deploy:
    - node themes/minimo/scripts/generate-search-index-lunr.js

deploy:
  provider: pages
  local_dir: public
  github_token: "$GH_TOKEN"
  skip_cleanup: true
  verbose: true
  keep-history: true
  on:
    branch: theme-update # to adapt
